ALTER TABLE "iceberg".users ADD COLUMN ID_ASSOCIATION INTEGER;
ALTER TABLE "iceberg".users ADD CONSTRAINT ID_ASSOCIATION_FK FOREIGN KEY (ID_ASSOCIATION) REFERENCES "iceberg".association (ID);

ALTER TABLE "iceberg".users ADD COLUMN IS_ROOT BOOLEAN DEFAULT FALSE;
ALTER TABLE "iceberg".users ADD COLUMN IS_ADMIN BOOLEAN DEFAULT FALSE;
ALTER TABLE "iceberg".users ADD COLUMN IS_MEMBER BOOLEAN DEFAULT FALSE;
ALTER TABLE "iceberg".users ADD COLUMN IS_VISITOR BOOLEAN DEFAULT FALSE;

ALTER TABLE "iceberg".users ADD CONSTRAINT USERS_UNIQUE UNIQUE (MAIL, ID_ASSOCIATION) ;

ALTER TABLE "iceberg".users DROP COLUMN NAME;

INSERT INTO "iceberg".users (MAIL, IS_ROOT) VALUES ('camille.levoye@gmail.com', true);
INSERT INTO "iceberg".users (MAIL, IS_ROOT) VALUES ('ludovicaernout@gmail.com', true);
INSERT INTO "iceberg".users (MAIL, IS_ROOT) VALUES ('elodiedelbecque@gmail.com', true);